//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransfer
    {
        public long Id { get; set; }
        public Nullable<long> SenderId { get; set; }
        public Nullable<long> ReceiverId { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblCustomer tblCustomer1 { get; set; }
    }
}
